export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED";
export const FETCH_MENU_START = "FETCH_MENU_START";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const POST_ORDER_START = "POST_ORDER_START";
export const POST_ORDER_FAILED = "POST_ORDER_FAILED";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";

export const FETCH_HISTORY_START = "FETCH_HISTORY_START";
export const FETCH_HISTORY_FAILED = "FETCH_HISTORY_FAILED";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
